version: "3.8"

networks:
    default:
        external: true

services:
   default:
        build: .
        ports:
            - "49999:49999"
        volumes:
            - m8cww0gcog400c4kws4kkc88-Admin Panel Volume:/instance
        environment:
            - FLASK_APP=app.py
            - FLASK_ENV=production
            - FLASK_DEBUG=0