"""Daily banners migration

Revision ID: 3a50aee2bd60
Revises: 82a72565d3be
Create Date: 2024-10-09 00:03:32.235682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a50aee2bd60'
down_revision = '82a72565d3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_banner_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_banner_item', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
